[package]
name = "pauli"
version = "0.2.0"
authors = ["maxime"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sprs = "0.9.3"
